library(dplyr)
data <- read.table("household_power_consumption.txt",sep = ';',header=T)
data$Date <- as.character(data$Date)
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- filter(data, Date > '2007-01-31',Date < '2007-02-03')
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 <- as.numeric(as.character(data$Sub_metering_3))
data$Time <- as.character(data$Time)
data$DateTime <- paste(data$Date,data$Time)
data$DateTime <- as.POSIXct(strptime(data$DateTime,format="%Y-%m-%d %H:%M:%S"),tz="EST5EDT")
png(file='plot3.png',height=480,width=480)

plot(data$DateTime,data$Sub_metering_1,type='l',ylab="Energy sub metering",xlab="")
lines(data$DateTime,data$Sub_metering_2,col="red")
lines(data$DateTime,data$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),lwd=c(2.5,2.5),col=c("black","red","blue"))
# hist(data$Global_active_power,breaks=15,main='Global Active Power', col = 'red',ylim = c(0,1200),xlab = 'Global Active Power (kilowatts)')
dev.off()